export class PermissionBody {
    userId: String;
    manageVendorView:Boolean=false;
    manageVendorDelete:Boolean=false;
    manageVendorWrite:Boolean=false;
    manageUserView:Boolean=false;
    manageUserWrite:Boolean=false;
    manageUserDelete:Boolean= false;
    manageCategoryView:Boolean=false;
    manageCategoryWrite:Boolean= false;
    manageCategoryDelete:Boolean= false;
    manageSubCategoryView:Boolean=false;
    manageSubCategoryWrite:Boolean= false;
    manageSubCategoryDelete:Boolean= false;
    manageBannerView:Boolean=false;
    manageBannerWrite:Boolean= false;
    manageBannerDelete:Boolean= false;
    manageDealView:Boolean=false;
    manageDealWrite:Boolean= false;
    manageDealDelete:Boolean= false;
    manageProductView:Boolean=false;
    manageProductWrite:Boolean= false;
    manageProductDelete:Boolean= false;
    manageOrderView:Boolean=false;
    manageOrderWrite:Boolean= false;
    manageOrderDelete:Boolean= false;
    manageInventryView:Boolean=false;
    manageInventryWrite:Boolean= false;
    manageInventryDelete:Boolean= false;
    manageDriverView:Boolean=false;
    manageDriverWrite:Boolean= false;
    manageDriverDelete:Boolean= false;
    manageGeofenceView:Boolean=false;
    manageGeofenceWrite:Boolean= false;
    manageGeofenceDelete:Boolean= false;
    manageTimesloatView:Boolean=false;
    manageTimesloatWrite:Boolean= false;
    manageTimesloatDelete:Boolean= false;
    manageCouponView:Boolean=false;
    manageCouponWrite:Boolean= false;
    manageCouponDelete:Boolean= false;
    manageSettingWrite:Boolean= false;
    manageSettingView:Boolean= false;
    manageTruckView:Boolean=false;
    manageTruckWrite:Boolean= false;
    manageTruckDelete:Boolean= false;
    manageBroadcastView:Boolean= false
    manageBroadcastWrite:Boolean= false
}